spring.application.name=kafka.producer
server.port=8083

# Kafka Config
spring.kafka.bootstrap-servers=kafka:9092
kafka.topic.name=demo-topic-2

# Optional for larger messages if needed
spring.kafka.producer.properties.max.request.size=104857600
spring.kafka.producer.properties.buffer.memory=134217728